### ISSUE TITLE
Beta Test Availability

### ISSUE THREAD

**Issue by Rafaelrico77** [jhuesser/bzu-jodel-clone#161]
Give more students access to the beta test ;)

**Comment by jhuesser** [comment]
1. it's alpha
2. We inform if there is a official alpha/beta to test.

Cleared the dev-DB on tuesday, because of our presentation.

**Comment by jhuesser** [comment]
quick update, if the last 10 milestones are closed, the alpha will be prepared and released (need to change some scripts.)
